project_name: tins-rpc
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: tins-rpc
    binary: tins-rpc
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    main: .
archives:
  - id: tins-rpc
    builds:
      - tins-rpc
    name_template: '{{.ProjectName}}-v{{.Version}}_{{.Os}}_{{.Arch}}'
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: zevfang
    name: tins-rpc