project_name: tins-rpc

before:
  hooks:
    - go mod tidy

archives:
  - id: tins-rpc
    files:
      - README.md
    builds:
      - tins-rpc
    name_template: '{{.ProjectName}}-v{{.Version}}_{{.Os}}_{{.Arch}}'
    format_overrides:
      - goos: windows
        format: zip

builds:
  - id: tins-rpc
    binary: tins-rpc
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: .

release:
  github:
    owner: zevfang
    name: tins-rpc