name: Go

on:
  push:
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.14.x, 1.17.x ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true
      id: go
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libwayland-dev libxkbcommon-dev bc
        go get .
        
    - name: Build
      run: go build -v ./...
